# Tensorflow2.0 小练习

In [1]:
import tensorflow as tf
import numpy as np

## 实现softmax函数

In [4]:
def softmax(x):
    ##########
    '''实现softmax函数，只要求对最后一维归一化，
    不允许用tf自带的softmax函数'''
    ##########

    # 答：
    # 对最后一维进行操作
    max_x = tf.reduce_max(x, axis=-1, keepdims=True)  # 防止数值溢出
    exp_x = tf.exp(x - max_x)
    sum_exp_x = tf.reduce_sum(exp_x, axis=-1, keepdims=True)
    prob_x = exp_x / sum_exp_x

    return prob_x

test_data = np.random.normal(size=[10, 5])
(softmax(test_data).numpy() - tf.nn.softmax(test_data, axis=-1).numpy())**2 <0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [5]:
def sigmoid(x):
    ##########
    '''实现sigmoid函数， 不允许用tf自带的sigmoid函数'''
    ##########

    # 答：
    prob_x = 1 / (1 + tf.exp(-x))
    
    return prob_x

test_data = np.random.normal(size=[10, 5])
(sigmoid(test_data).numpy() - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [7]:
def softmax_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########

    # 答：
    # Softmax 交叉熵公式：-sum(label * log(prob))
    epsilon = 1e-10  # 防止 log(0) 导致数值不稳定
    loss = -tf.reduce_mean(tf.reduce_sum(label * tf.math.log(prob + epsilon), axis=-1))

    return loss

test_data = np.random.normal(size=[10, 5])
prob = tf.nn.softmax(test_data)
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.

((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label, test_data))
  - softmax_ce(prob, label))**2 < 0.0001).numpy()

True

## 实现 sigmoid 交叉熵loss函数

In [8]:
def sigmoid_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########

    # 答：
    # Sigmoid 交叉熵公式：-sum(label * log(prob) + (1 - label) * log(1 - prob))
    epsilon = 1e-10  # 防止 log(0) 导致数值不稳定
    loss = -tf.reduce_mean(label * tf.math.log(prob + epsilon) + (1 - label) * tf.math.log(1 - prob + epsilon))

    return loss

test_data = np.random.normal(size=[10])
prob = tf.nn.sigmoid(test_data)
label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print (label)

((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data))- sigmoid_ce(prob, label))**2 < 0.0001).numpy()


[0. 0. 1. 1. 0. 0. 1. 0. 0. 1.]


True

In [10]:
# 测试 Softmax
test_data = tf.random.normal([10, 5])
print("Softmax 测试结果：", tf.reduce_all((softmax(test_data).numpy() - tf.nn.softmax(test_data, axis=-1).numpy())**2 < 0.0001))

# 测试 Sigmoid
test_data = tf.random.normal([10, 5])
print("Sigmoid 测试结果：", tf.reduce_all((sigmoid(test_data).numpy() - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001))

# 测试 Softmax 交叉熵
test_data = tf.random.normal([10, 5])
prob = tf.nn.softmax(test_data)
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)] = 1.
print("Softmax 交叉熵测试结果：", tf.reduce_all((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label, test_data)) - softmax_ce(prob, label))**2 < 0.0001).numpy())

# 测试 Sigmoid 交叉熵
test_data = tf.random.normal([10])
prob = tf.nn.sigmoid(test_data)
label = tf.cast(np.random.randint(0, 2, 10), test_data.dtype)  # 使用 tf.cast 转换数据类型
print("Sigmoid 交叉熵测试结果：", tf.reduce_all((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data)) - sigmoid_ce(prob, label))**2 < 0.0001).numpy())

Softmax 测试结果： tf.Tensor(True, shape=(), dtype=bool)
Sigmoid 测试结果： tf.Tensor(True, shape=(), dtype=bool)
Softmax 交叉熵测试结果： True
Sigmoid 交叉熵测试结果： True
